Feature/documentation pages
unipept/unipept-web pull request #5
Opened 2022-08-18 14:17 UTC by tibvdm

This PR will add the documentation webpages

2022-08-22 07:21 UTC, pverscha requested changes, later dismissed
Not a lot of remarks, the only thing that we should improve is the contrast between the text and the background. The main color of the text is now mostly a dark gray, but I think it would be better if all large chunks of text are black.

![image](https://user-images.githubusercontent.com/9608686/185862623-82a9049a-99da-49c9-975f-f1f38d056db5.png)

2022-08-22 07:21 UTC, pverscha commented on src/components/pages/apidocs/Pept2ProtPage.vue
> +        <h3 class="font-weight-regular grey--text">Returns the set of UniProt entries containing a given tryptic peptide.</h3>
Try to increase the contrast of the text on this line, it's a little hard to read against the background.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/9608686/185644841-52d36ca4-1b1d-41fb-ae8c-abf46d05dabf.png">

2022-08-22 12:28 UTC, tibvdm commented
Links are added and v-card contrast should now be fixed everywhere.

2022-08-22 12:54 UTC, pverscha reviewed
Contrast is much better now! :)

2022-11-06 09:57 UTC, pverscha commented
During my work on adding the documentation pages for the desktop app, I stumbled upon a few minor things that I wanted to write down:

* [ ] Multiple components have the same name. They are all kept in a separate directory, so this isn't really a technical issue, but I think this could cause confusion. My suggestion is to rename the components called `OverviewPage` to, for example, `MetagenomicsOverviewPage`.
* [ ] In the `assets` directory, all images (and other assets) required for the documentation pages are stored in one big directory. This is fine as long as there are only a few assets, but at this point it starts to become a bit "cluttered". It's better to structure the assets directory a bit more and move the images to subdirectories per documentation category (api, cli, ...).

2023-01-12 13:42 UTC, merged